
export const SET_IMAGE_REQUEST_STR = 'SET_IMAGE_REQUEST_STR';

export const SEARCH_IMAGE_REQUEST = 'SEARCH_IMAGE_REQUEST';
export const SEARCH_IMAGE_SUCCESS = 'SEARCH_IMAGE_SUCCESS';
export const SEARCH_IMAGE_FAILURE = 'SEARCH_IMAGE_FAILURE';
